trigger:
- main

pool:
  name: 'Self-hosted-pool'

steps:
- script: "echo Hello, World!"
  displayName: 'Checking pipeline is able to use SHIR machine'

- task: AzurepowerShell@5
  inputs:
    displayName: 'Create Resource Group and VM'
    azureSubscription: 'azure-devops-svc'
    ScriptType: 'inlineScript'
    Inline: |
      $resourceGroupName = "rg-dev-vm2"
      $location = "westeurope"
      $vmName = "vm-dev-webserver2"
      
      # Create Resource Group
      New-AzResourceGroup -Name $resourceGroupName -Location $location
      
      # Create Virtual Machine
      New-AzVM -ResourceGroupName $resourceGroupName -Name $vmName -Location $location -Image "Win2019Datacenter" -Size "Standard_DS1_v2" -Credential (Get-Credential)
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    failOnStandardError: true


