pool:
  name: 'Self-hosted-pool'


stages:
- stage: Prepare
  variables:
    environmentName: 'dev'
    # Stage level variable with the service connection name
    # Evaluates to conenctionString-test-001
    azureSubscription: 'azure-devops-svc'

  jobs:
  - job: RunStuff
    steps:
    - task: AzureCLI@2
      inputs:
        # Set this input to the computed value
        azureSubscription: ${{ variables.azureSubscription }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: 'echo Hello ${{ variables.azureSubscription }}'

    - task: AzurePowerShell@5
      inputs:
        # Set this input to the computed value
        azureSubscription: ${{ variables.azureSubscription }}
        azurePowerShellVersion: 'LatestVersion'
        scriptType: 'InlineScript'
        inline: Write-Host "Hello power ${{ variables.azureSubscription }}"