trigger:
- main

pool:
  name: 'Self-hosted-pool'

steps:
- script: "echo Hello, World!"
  displayName: 'Check Azure CLI Version'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-svc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name rg-dev-vm2 --location westeurope
      az vm create \
        --resource-group rg-dev-vm2 \
        --name vm-dev-webserver2 \
        --image UbuntuLTS \
        --admin-username azureuser \
        --admin-password $(ADMINPASS)
    displayName: 'Create Azure VM'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-svc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm start --resource-group rg-dev-vm2 --name vm-dev-webserver2
    displayName: 'Start Azure VM'
- task: AzureCLI@2
  inputs: 
    azureSubscription: 'azure-devops-svc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm run-command invoke --resource-group rg-dev-vm2 --name vm-dev-webserver2 --command-id RunShellScript --scripts "echo Hello, World!"
    displayName: 'Run Command on Azure VM'