trigger:
- main

pool:
  name: 'Self-hosted-pool'

steps:
- script: "echo Hello, World!"
  displayName: 'Checking pipeline is able to use SHIR machine'

- task: AzurepowerShell@5
  inputs:
    displayName: 'Create Resource Group and VM'
    azureSubscription: 'azure-devops-svc'
    ScriptType: 'inlineScript'
    Inline: |
      $resourceGroupName = "MyResourceGroup"
      $location = "WestEurope"
      $vmName = "MyLinuxVM"
      $vmSize = "Standard_B1s" 
      $image = "UbuntuLTS" 
      $adminUsername = "azureuser"
      $password = ${env:ADMINPASS}

      New-AzResourceGroup -Name $resourceGroupName -Location $location

    azurePowerShellVersion: 'LatestVersion'


