trigger:
- main

pool:
  name: 'Self-hosted-pool'

steps:
- script: "echo Hello, World!"
  displayName: 'Checking pipeline is able to use SHIR machine'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'azure-devops-svc'
    ScriptType: 'InlineScript'
    Inline: 'New-AzResourceGroup -Name ''myResourceGroup'' -Location ''eastus'''
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true