trigger:
- main

pool:
  name: 'Self-hosted-pool'

steps:
- script: "echo Hello, World!"
  displayName: 'Checking pipeline is able to use SHIR machine'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-devops-svc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name rg-dev-vm2 --location westeurope
